name: Update Last.fm

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Last.fm stats
        uses: eddiejaoude/lastfm-api@main
        with:
          username: ${{ secrets.LASTFM_USERNAME }}
          api_key: ${{ secrets.LASTFM_API_KEY }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Last.fm stats"
