name: Update Last.fm

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          pip install requests

      - name: Update Last.fm README
        env:
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |
          python scripts/lastfm.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Last.fm playing status"
